# Site settings
title: 从头再来
email: fancycat@163.com
description: "随便记点代码碎片。"
baseurl: "http://go2feel.github.io"
url: "http://go2feel.github.io"

# Build settings
markdown: kramdown
permalink: pretty
